spring:
  application:
    name: mcp-prototype
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mcp_support_desk}
    username: ${SPRING_DATASOURCE_USERNAME:mcp_support_desk}
    password: ${SPRING_DATASOURCE_PASSWORD:mcp_support_desk}
  ai:
    mcp:
      server:
        name: mcp-support-desk
        version: 0.0.1
        protocol: STREAMABLE
        type: SYNC
        annotation-scanner:
          enabled: true
